version: "3"
services:
    library-db:
        image: mariadb:10.5
        container_name: library-db
        volumes:
            - "./data:/var/lib/mysql"
        ports:
            - "8080:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - library
        restart: unless-stopped

    library-api:
        image: amoraresco/it-academy-project:latest
        container_name: library-api
        links:
            - library-db
            - library-redis
        ports:
            - "88:80"
            - "882:22"
        volumes:
            - "./:/var/www/html"
        networks:
            - library
        restart: unless-stopped

    library-mailhog:
        image: mailhog/mailhog
        container_name: library-mailhog
        ports:
            - "8825:8025"
            - "8125:1025"
        networks:
            - library

    library-redis:
        image: redis:3.0
        container_name: library-redis
        volumes:
            - "./data/redis/cache/data:/data"
        ports:
            - "8379:6379"
        restart: unless-stopped
        networks:
            - library

networks:
    library:
        driver: bridge
